# [build-system]
# requires = ["flit_core >=3.2,<4"]
# build-backend = "flit_core.buildapi"

# [project]
# name = "ERP USERSIDE Documetation"
# authors = [{name = "Anton Dyuringer", email = "office@userside.eu"}]
# dynamic = ["version", "description"]
